name: ce
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
    - pip
    - pip:
    - aiodns==2.0.0
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - aplus==0.11.0
    - astropy==4.2
    - atomicwrites==1.4.0
    - blessings==1.7
    - boto3==1.16.48
    - botocore==1.19.48
    - bpemb==0.3.2
    - bqplot==0.12.19
    - branca==0.4.2
    - cchardet==2.1.7
    - colorful==0.5.4
    - cycler==0.10.0
    - cython==0.29.14
    - dask==2.19.0
    - deprecated==1.2.10
    - distributed==2.19.0
    - filelock==3.0.12
    - flair==0.6.1
    - flake8==3.8.4
    - ftfy==5.8
    - future==0.18.2
    - gdown==3.12.2
    - gensim==3.8.3
    - google-api-core==1.24.1
    - googleapis-common-protos==1.52.0
    - gpustat==0.6.0
    - hiredis==1.1.0
    - hyperopt==0.2.5
    - iniconfig==1.1.1
    - ipdb==0.13.4
    - ipydatawidgets==4.2.0
    - ipyleaflet==0.13.6
    - ipympl==0.6.2
    - ipyvolume==0.5.2
    - ipyvue==1.4.1
    - ipyvuetify==1.5.1
    - ipywebrtc==0.5.0
    - janome==0.4.1
    - jmespath==0.10.0
    - jupyterlab-widgets==1.0.0
    - konoha==4.6.2
    - langdetect==1.0.8
    - llvmlite==0.34.0
    - lrcurve==2.1.0
    - lxml==4.5.2
    - mccabe==0.6.1
    - mpld3==0.3
    - natsort==7.1.0
    - networkx==2.5
    - nltk==3.3
    - numpy==1.18.5
    - nvidia-ml-py3==7.352.0
    - opencensus==0.7.11
    - opencensus-context==0.1.2
    - overrides==3.0.0
    - pandas==1.1.4
    - parso==0.8.1
    - pip==20.3.3
    - pluggy==0.13.1
    - progressbar2==3.53.1
    - psutil==5.8.0
    - py==1.9.0
    - py-spy==0.3.3
    - pyarrow==2.0.0
    - pycares==3.1.1
    - pycodestyle==2.6.0
    - pyerfa==1.7.1.1
    - pyflakes==2.2.0
    - pytest==6.1.1
    - python-utils==2.4.0
    - pythreejs==2.2.1
    - ray==1.1.0
    - redis==3.5.3
    - s3fs==0.2.2
    - s3transfer==0.3.3
    - sacremoses==0.0.43
    - segtok==1.5.10
    - sentencepiece==0.1.91
    - shapely==1.7.1
    - smart-open==3.0.0
    - spacy-wordnet==0.0.4
    - sqlitedict==1.7.0
    - tabulate==0.8.7
    - tokenizers==0.8.1rc2
    - traittypes==0.2.1
    - transformers==3.3.1
    - vaex==3.0.0
    - vaex-arrow==0.5.1
    - vaex-astro==0.7.0
    - vaex-core==2.0.3
    - vaex-hdf5==0.6.0
    - vaex-jupyter==0.5.2
    - vaex-ml==0.9.0
    - vaex-server==0.3.1
    - vaex-viz==0.4.0
    - vulture==2.1
    - wrapt==1.12.1
    - xarray==0.16.2
    - xlsxwriter==1.3.7
